// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Types of authentication token
type Flavor int32

const (
	Flavor_AUTH_NONE Flavor = 0
	Flavor_AUTH_SYS  Flavor = 1
)

var Flavor_name = map[int32]string{
	0: "AUTH_NONE",
	1: "AUTH_SYS",
}

var Flavor_value = map[string]int32{
	"AUTH_NONE": 0,
	"AUTH_SYS":  1,
}

func (x Flavor) String() string {
	return proto.EnumName(Flavor_name, int32(x))
}

func (Flavor) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type Token struct {
	Flavor               Flavor   `protobuf:"varint,1,opt,name=flavor,proto3,enum=auth.Flavor" json:"flavor,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetFlavor() Flavor {
	if m != nil {
		return m.Flavor
	}
	return Flavor_AUTH_NONE
}

func (m *Token) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Token structure for AUTH_SYS flavor cred
type Sys struct {
	Stamp                uint64   `protobuf:"varint,1,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Machinename          string   `protobuf:"bytes,2,opt,name=machinename,proto3" json:"machinename,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Groups               []string `protobuf:"bytes,5,rep,name=groups,proto3" json:"groups,omitempty"`
	Secctx               string   `protobuf:"bytes,6,opt,name=secctx,proto3" json:"secctx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sys) Reset()         { *m = Sys{} }
func (m *Sys) String() string { return proto.CompactTextString(m) }
func (*Sys) ProtoMessage()    {}
func (*Sys) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Sys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sys.Unmarshal(m, b)
}
func (m *Sys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sys.Marshal(b, m, deterministic)
}
func (m *Sys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sys.Merge(m, src)
}
func (m *Sys) XXX_Size() int {
	return xxx_messageInfo_Sys.Size(m)
}
func (m *Sys) XXX_DiscardUnknown() {
	xxx_messageInfo_Sys.DiscardUnknown(m)
}

var xxx_messageInfo_Sys proto.InternalMessageInfo

func (m *Sys) GetStamp() uint64 {
	if m != nil {
		return m.Stamp
	}
	return 0
}

func (m *Sys) GetMachinename() string {
	if m != nil {
		return m.Machinename
	}
	return ""
}

func (m *Sys) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Sys) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Sys) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Sys) GetSecctx() string {
	if m != nil {
		return m.Secctx
	}
	return ""
}

// Token and verifier are expected to have the same flavor type.
type Credential struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Verifier             *Token   `protobuf:"bytes,2,opt,name=verifier,proto3" json:"verifier,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *Credential) GetVerifier() *Token {
	if m != nil {
		return m.Verifier
	}
	return nil
}

func (m *Credential) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

// GetCredentialResp represents the result of a request to fetch authentication
// credentials.
type GetCredentialResp struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Cred                 *Credential `protobuf:"bytes,2,opt,name=cred,proto3" json:"cred,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCredentialResp) Reset()         { *m = GetCredentialResp{} }
func (m *GetCredentialResp) String() string { return proto.CompactTextString(m) }
func (*GetCredentialResp) ProtoMessage()    {}
func (*GetCredentialResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *GetCredentialResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCredentialResp.Unmarshal(m, b)
}
func (m *GetCredentialResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCredentialResp.Marshal(b, m, deterministic)
}
func (m *GetCredentialResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCredentialResp.Merge(m, src)
}
func (m *GetCredentialResp) XXX_Size() int {
	return xxx_messageInfo_GetCredentialResp.Size(m)
}
func (m *GetCredentialResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCredentialResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCredentialResp proto.InternalMessageInfo

func (m *GetCredentialResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetCredentialResp) GetCred() *Credential {
	if m != nil {
		return m.Cred
	}
	return nil
}

// ValidateCredentialReq represents a request to verify a set of authentication
// credentials.
type ValidateCredentialReq struct {
	Cred                 *Credential `protobuf:"bytes,1,opt,name=cred,proto3" json:"cred,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ValidateCredentialReq) Reset()         { *m = ValidateCredentialReq{} }
func (m *ValidateCredentialReq) String() string { return proto.CompactTextString(m) }
func (*ValidateCredentialReq) ProtoMessage()    {}
func (*ValidateCredentialReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *ValidateCredentialReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateCredentialReq.Unmarshal(m, b)
}
func (m *ValidateCredentialReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateCredentialReq.Marshal(b, m, deterministic)
}
func (m *ValidateCredentialReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateCredentialReq.Merge(m, src)
}
func (m *ValidateCredentialReq) XXX_Size() int {
	return xxx_messageInfo_ValidateCredentialReq.Size(m)
}
func (m *ValidateCredentialReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateCredentialReq.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateCredentialReq proto.InternalMessageInfo

func (m *ValidateCredentialReq) GetCred() *Credential {
	if m != nil {
		return m.Cred
	}
	return nil
}

// ValidateCredentialResp represents the result of a request to validate
// authentication credentials.
type ValidateCredentialResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateCredentialResp) Reset()         { *m = ValidateCredentialResp{} }
func (m *ValidateCredentialResp) String() string { return proto.CompactTextString(m) }
func (*ValidateCredentialResp) ProtoMessage()    {}
func (*ValidateCredentialResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *ValidateCredentialResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateCredentialResp.Unmarshal(m, b)
}
func (m *ValidateCredentialResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateCredentialResp.Marshal(b, m, deterministic)
}
func (m *ValidateCredentialResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateCredentialResp.Merge(m, src)
}
func (m *ValidateCredentialResp) XXX_Size() int {
	return xxx_messageInfo_ValidateCredentialResp.Size(m)
}
func (m *ValidateCredentialResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateCredentialResp.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateCredentialResp proto.InternalMessageInfo

func (m *ValidateCredentialResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ValidateCredentialResp) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterEnum("auth.Flavor", Flavor_name, Flavor_value)
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Sys)(nil), "auth.Sys")
	proto.RegisterType((*Credential)(nil), "auth.Credential")
	proto.RegisterType((*GetCredentialResp)(nil), "auth.GetCredentialResp")
	proto.RegisterType((*ValidateCredentialReq)(nil), "auth.ValidateCredentialReq")
	proto.RegisterType((*ValidateCredentialResp)(nil), "auth.ValidateCredentialResp")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x0a, 0x6d, 0x03, 0x03, 0xdf, 0x17, 0xbe, 0x8d, 0x92, 0x1e, 0x6b, 0x83, 0x91, 0x78,
	0xe0, 0x80, 0x67, 0x0f, 0xc4, 0xf8, 0xe3, 0x84, 0x71, 0x8b, 0x26, 0x9e, 0xcc, 0xda, 0x0e, 0xb0,
	0x11, 0xda, 0xba, 0xbb, 0x25, 0xfa, 0x97, 0xf8, 0xef, 0x9a, 0x4e, 0x37, 0x48, 0x8c, 0x72, 0x9b,
	0x37, 0x6f, 0xde, 0xbc, 0x37, 0x9b, 0x05, 0x10, 0xa5, 0x59, 0x8e, 0x0a, 0x95, 0x9b, 0x9c, 0xb9,
	0x55, 0x1d, 0x4d, 0xc0, 0x9b, 0xe5, 0x2f, 0x98, 0xb1, 0x01, 0xf8, 0xf3, 0x95, 0xd8, 0xe4, 0x2a,
	0x70, 0x42, 0x67, 0xf8, 0x6f, 0xdc, 0x1d, 0xd1, 0xec, 0x15, 0xf5, 0xb8, 0xe5, 0x18, 0x03, 0x37,
	0x15, 0x46, 0x04, 0x8d, 0xd0, 0x19, 0x76, 0x39, 0xd5, 0xd1, 0x87, 0x03, 0xcd, 0xf8, 0x5d, 0xb3,
	0x03, 0xf0, 0xb4, 0x11, 0xeb, 0x82, 0x16, 0xb8, 0xbc, 0x06, 0x2c, 0x84, 0xce, 0x5a, 0x24, 0x4b,
	0x99, 0x61, 0x26, 0xd6, 0x48, 0xc2, 0x36, 0xdf, 0x6d, 0x55, 0x3b, 0x4b, 0x8d, 0x2a, 0x68, 0x12,
	0x45, 0x75, 0xb5, 0x6b, 0xa1, 0xf2, 0xb2, 0x08, 0x5c, 0x6a, 0xd6, 0x80, 0xf5, 0xc1, 0xa7, 0x42,
	0x07, 0x5e, 0xd8, 0x1c, 0xb6, 0xb9, 0x45, 0x55, 0x5f, 0x63, 0x92, 0x98, 0xb7, 0xc0, 0xa7, 0x71,
	0x8b, 0xa2, 0x02, 0xe0, 0x42, 0x61, 0x8a, 0x99, 0x91, 0x62, 0xc5, 0x8e, 0xc0, 0x33, 0xd5, 0xa9,
	0x94, 0xaf, 0x33, 0xee, 0xd4, 0x07, 0xd2, 0xf5, 0xbc, 0x66, 0xd8, 0x09, 0xb4, 0x36, 0xa8, 0xe4,
	0x5c, 0xa2, 0xa2, 0xa4, 0xdf, 0xa6, 0xb6, 0x64, 0xe5, 0x98, 0x2b, 0xb9, 0x90, 0x99, 0x4d, 0x6d,
	0x51, 0x74, 0x07, 0xff, 0xaf, 0xd1, 0x7c, 0x99, 0x72, 0xd4, 0x14, 0x5b, 0x1b, 0x61, 0x4a, 0x4d,
	0xce, 0x1e, 0xb7, 0x88, 0x0d, 0xc0, 0x4d, 0x14, 0xa6, 0xd6, 0xa9, 0x57, 0x3b, 0xed, 0x68, 0x89,
	0x8d, 0xce, 0xe1, 0xf0, 0x41, 0xac, 0x64, 0x2a, 0x0c, 0xee, 0xee, 0x7d, 0xdd, 0xca, 0x9d, 0xbd,
	0xf2, 0x18, 0xfa, 0x3f, 0xc9, 0xf7, 0xc4, 0xda, 0xbe, 0x53, 0xe3, 0xb7, 0x77, 0x3a, 0x3d, 0x06,
	0xbf, 0xfe, 0x18, 0xec, 0x2f, 0xb4, 0x27, 0xf7, 0xb3, 0x9b, 0xa7, 0xe9, 0xed, 0xf4, 0xb2, 0xf7,
	0x87, 0x75, 0xa1, 0x45, 0x30, 0x7e, 0x8c, 0x7b, 0xce, 0xb3, 0x4f, 0x3f, 0xed, 0xec, 0x33, 0x00,
	0x00, 0xff, 0xff, 0x80, 0xa9, 0xc4, 0xb0, 0x77, 0x02, 0x00, 0x00,
}
